### ISSUE TITLE
Freezing/superfast catch-up during watching

### ISSUE THREAD

**Issue by djarumlights** [Goldenfreddy0703/Otaku-Testing#25]
Hello! 

I've noticed in the past couple updates an odd playback issue that's not present in the non-testing version.

Lately, whatever I'm watching will suddenly freeze, and instead of the buffer circle popping up (my ISP kinda blows, so I expect it on odd occasion), the playback will suddenly resume in a fast-forward manner. Once it catches up with itself, it'll go back to normal. When this happens, I note that I can't back up 30 seconds-1 minute to rehash the turbo speed section, as the time bar appears to get quite confused with where it actually is supposed to be. 

I'd say it's started doing this in the last ... 2-3 weeks?

I'm not using a debrid or the like, just straight embed streaming.

**Comment by Goldenfreddy0703** [comment]
I'm kinda confused but is this happening when you start the anime?

**Comment by djarumlights** [comment]
It's happening at random points thru the episode or movie being played. No rhyme or reason to when it might happen.

**Comment by djarumlights** [comment]
[
https://www.mediafire.com/file/997yut1lrlpt68f/PXL_20250201_064633909.TS.mp4/file
](url)

There are no subtitles in this clip, but note now suddenly it just zooms forward..

**Comment by Goldenfreddy0703** [comment]
Hey so from looking at this, we think itx mostly problems with the embed server side so basically some servers maybe having streaming problems which is why this is happening and there is nothing we an do unfortunately but if you want to speed up the cache or something like that. Mess with kodi's Caching setting that are in Services or have the addon Openwizard do that for you sense its still a great addon. 
https://github.com/a4k-openproject/repository.openwizard

![Image](https://github.com/user-attachments/assets/54d43daf-9bbd-414c-9ace-d35fb294dd83)
Hope this helps and hope this could help speed up your embed streams.

**Comment by joezito129** [comment]
Does this usually happen at the begin of the episode (first 5 min) or does this still occur after the 5 min mark?

**Comment by djarumlights** [comment]
Hey, sorry for the delay in responding!

It happens all throughout any given episode of any given show. I'll play with the cache and the add-on referenced to see if that helps.

It was just odd that it occurs in the test version and not the main release (I keep both because some shows disappeared from the main release for whatever reason).

**Comment by djarumlights** [comment]
I bumped the cache up from 20 to 32 then 64. It actually seemed to make things worse with how far it decides to blow forward before catching up and resuming normal playback. Up to a full two minutes of watch time condensed into 20-30 seconds.

Fwiw, this is a Hisense projector that runs on an Android TV OS.

**Comment by Goldenfreddy0703** [comment]
Heyyy @Gujal00 sorry to bother you but any idea on why this could be happening on Otaku Testing but not Otaku?

**Comment by djarumlights** [comment]
Another quirk I notice during all this (and it is consistent across multiple shows): 

Time bar shows up to two minutes remaining in an episode if I choose not to skip the end credits to catch a scene. It's quite wrong. 

Almost like the player is trying to match up with incorrect time data? 

Fwiw, lately, some of the 5-15 second freezes HAVE been accompanied by the buffering circle, but it still zooms forward at 2-5x speed instead of halting, catching up with itself, and resuming normally. I've also been checking to see if a particular provider may be at fault, but pahe, h!, and others all behave the same

**Comment by Goldenfreddy0703** [comment]
Hey @djarumlights sense you are an embed person, i would like you to enable "Use Kodi's Preferred Language Settings" in the Playback category of addon settings  and see if that fixes most of your issues with the embeds. 

If you could do that, that would be great. Thanks

**Comment by djarumlights** [comment]
Giving it a try and will report back!

**Comment by Goldenfreddy0703** [comment]
> Giving it a try and will report back!

Awesome thank you very much, im hoping its due to are subtitle and audio code.

**Comment by Goldenfreddy0703** [comment]
Hey @djarumlights , i found someone else to help me test and i made a release, hopefully this fixes the caching issue with the embed. Hope this helps and thanks.

**Comment by djarumlights** [comment]
Sounds good.

Unfortunately the preferred language option showed no change in the behavior. Will advise once new update hits on my end and let you know how it goes.

**Comment by djarumlights** [comment]
Well.... 

Unfortunately the issue still persists. Is there any system info or log file I can send to possibly assist in isolating where the hiccup might be?

**Comment by Goldenfreddy0703** [comment]
Hey sorry I never got back to you, your could send a log if you log if you like but it might not do so much, in your kodi settings enable debug logging, try to reproduce this issue and then use the kodi log uploader.

https://kodi.wiki/view/Add-on:Kodi_Logfile_Uploader

**Comment by Eskander** [comment]
Hello, I also have the same issue for a few weeks now (I thought it was related to my setup). I think it only happens with the Kwik embed but don't quote me on that. The cache settings in Kodi seem to have no effect.

**Comment by epidoma** [comment]
@Goldenfreddy0703 
yea same issue, but it works correctly in normal otaku. So ill stay with that for time beeing.
hers a log if it helps solve this, i see lots of errors.

[error.log](https://github.com/user-attachments/files/18934580/error.log)

**Comment by Goldenfreddy0703** [comment]
@Gujal00 would you mind taking a look at this guys log, I have a small feeling that there could be something wrong with the client when we removed the six module. 

https://github.com/user-attachments/files/18934580/error.log

**Comment by Goldenfreddy0703** [comment]
Hey guys, i looked into the player and optimized the crap out of it and added some threading. Its kinda experimental but hopefully this fixes the caching issues as well as freezing and super fast. Im going to close this but if issues do persist, please reply and we will open this back up.
Thanks

**Comment by Eskander** [comment]
Unfortunately, the latest version didn't help with the issue.

Here's another debug log using the latest version: [kodi.log](https://github.com/user-attachments/files/19043548/kodi.log)

**Comment by Goldenfreddy0703** [comment]
Ugh.....I thought it did.

**Comment by Goldenfreddy0703** [comment]
> Unfortunately, the latest version didn't help with the issue.
> 
> Here's a debug log using the latest version: [kodi.log](https://github.com/user-attachments/files/19043548/kodi.log)
> 
> Edit: And another one using a different provider: [kodi.log](https://github.com/user-attachments/files/19043652/kodi.log)

Hey question,, i personally think i fixed it, did you try clearing cache and rebuilding database by anychance and could you try testing again?

**Comment by Eskander** [comment]
So, I tried clearing the cache and rebuilding the database as recommended, but the issue is still there.

Here's a screencast showing how the bug occurs in practice. You can see how the player hangs at 03:03, then jumps to 03:20, skipping 17 seconds forward. This happens multiple times during playback of any episode.

I'd like to note that this only happens in Otaku Testing, not old Otaku, even when using the exact same streaming file. So that kinda rules out issues with my setup or the streaming provider.

https://github.com/user-attachments/assets/484f75c6-21af-4de2-9505-ad71fb19851d

**Comment by Goldenfreddy0703** [comment]
Ok interesting, small question, is this from Animepeha by any chance?

**Comment by Eskander** [comment]
Yes. Though yesterday I provided logs using both Pahe and Gogo.

**Comment by Goldenfreddy0703** [comment]
Ok im not closing this issue just yet but i would like anyone to test my latest version so we can confirm that this issue is resolved. 
@Eskander Please test if you could. 

I am 100% confident that i have finally fixed this bug. I tested and optimized the player to be better and i have also optimized inputstream adaptive as well. I hope this issue will be closed very very soon.

**Comment by Goldenfreddy0703** [comment]
Ok so i had a few people test recently and im confident that i have finally fixed this bug so im gonna close this but if anyone tells me that its not fixed, make sure you clear the cache and rebuild the database just incase. 
Thanks

**Comment by Eskander** [comment]
I confirm this was indeed fixed 🚀

**Comment by Goldenfreddy0703** [comment]
Yes, i knew it. Thank you
Apparently it was a small coding issue with inputstream adaptive this whole time but thanks to this issue. I managed to optimize player and other stuff as well.
Thanks

**Comment by djarumlights** [comment]
Following up, and apologies for the lag in doing so.


Nailed it! We are clean and clear with no hiccups, binding, rushing, or skipping now. Thank you for your tenacity in resolving!!!
